name: Build and Deploy Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Configuration de Docker Buildx pour supporter plusieurs architectures (si besoin)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Étape 3: Connexion à Azure via Docker
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <NomDeVotreACR>.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      # Étape 4: Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t <NomDeVotreACR>.azurecr.io/my-container:v1 .

      # Étape 5: Push de l'image Docker vers ACR
      - name: Push Docker image to Azure Container Registry
        run: |
          docker push <NomDeVotreACR>.azurecr.io/my-container:v1

      # Étape 6: Déployer l'image Docker sur Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <NomDeVotreWebAppAzure>
          slot-name: Production
          images: <NomDeVotreACR>.azurecr.io/my-container:v1
