name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche l'action lorsque vous poussez sur la branche main (ou master, selon votre configuration)

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu sur GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Récupère le code du dépôt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour les builds multi-plateformes

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Action GitHub pour se connecter à Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Nom d'utilisateur Docker depuis les secrets
        password: ${{ secrets.DOCKER_TOKEN }}     # Token Docker depuis les secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Action GitHub pour builder et pousser l'image Docker
      with:
        context: .  # Contexte de build (dossier où se trouve le Dockerfile)
        push: true  # Pousse l'image vers Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/my-docker-website:latest  # Tag de l'image à pousser

